### ISSUE TITLE
Consider weakening return sentries to support compiler outlining

### ISSUE THREAD

**Issue by rmn30** [CHERIoT-Platform/cheriot-sail#85]
As per https://github.com/CHERIoT-Platform/llvm-project/issues/46 the current restrictions on return sentries cause difficulties for compiler outlining because it may use a non-standard link register. Currently `cjal` / `cjalr` always produce a return sentry in the link register which can only be used to return via `cret` (i.e `cjalr` with `cd == $cnull` and `cs1 == $cra`).

For reference here is the relevant table for `cjalr` from the ISA doc: ![Screenshot 2024-11-13 111246](https://github.com/user-attachments/assets/7de91568-9979-498e-9c17-99b4cb1e4c25) 

We could relax the ISA to permit using a non-standard link register by modifying `cjal` / `cjalr` where `cd` is not `$cra` such that they produce either 1) an unsealed capability or 2) a forward interrupt-inheriting sentry in the link register.  This would permit a return using `cjalr` with `cd == $cnull` and `cs1 != $cra`. Of these 1) is preferable as it does not introduce the ability to create forward sentries, which is not currently possible without a capability with the appropriate sealing permission. It is already possible to create unsealed capabilities derived from PCC.

**Comment by davidchisnall** [comment]
If we made a non-cra link register provide an unsealed capability, then the following two sequences are equivalent:

```asm
  cjal {target}, ct0
```

```asm
0:
  auipcc ct0, %cheriot_compartment_hi(1f)
  cincoffset ct0, ct0, %cheriot_compartment_lo_i(0b)
  b  {target}
1:
```

In both cases, you return with `cjr ct0`, which is already permitted.

I *believe* this means that there is no security implication and the relaxation on `cjal[r]` simply allows a code-size reduction by folding three instructions into one.

**Comment by rmn30** [comment]
As David points out this doesn't really weaken the current model at all. It really just fixes an anomaly in the above table where row three is not currently that useful: it can be used for making a function call with a non-standard link register but the called function has to move that register into `$cra` in order to return to it, which probably defeats the point of using a non-standard link register. The important thing is that calls to interrupt enabling / disabling sentries must use `ra` so that the called function can definitely restore the previous interrupt stance.

**Comment by vmurali** [comment]
Another thing to note is that, in a call to a library, if a caller compartment wishes to sanitize the arguments and force the library to only use the correct return entry points (i.e. not trust the library), it can always use `$cra` as the link register in the call.

**Comment by resistor** [comment]
I did a measurement with and without outlining disabled. Re-enabling MachineOutliner will save us approximately 4.4% code size (according to `scripts/output_code_size.sh`) on the CheriotRTOS test suite binary. As such I think it's definitely worthwhile to push ahead on getting this change in.

**Comment by resistor** [comment]
Is this supported in all necessary simulators, including `mpact`, such that I can re-enable it in the toolchain?

**Comment by vmurali** [comment]
Mpact just added the support for this. But ibex doesn't have this, so I am
not sure why it was already committed in sail

**Comment by davidchisnall** [comment]
It goes in Sail first, then implementations catch up.  

The Ibex bit was done two days ago, I believe (@kliuMsft can confirm), but I forgot that we still need to bump the submodule in SAFE to pick it up in the dev container.  We need to do that.

Sonata 1.0 and 0.2 don't include the Ibex fix, so we should probably have a compiler flag to disable it that we can add to the build system.

**Comment by kliuMsft** [comment]
@davidchisnall I have bumped cheriot-safe to link to the latest (ISA1.0 release) version of cheriot-ibex.

**Comment by resistor** [comment]
> Sonata 1.0 and 0.2 don't include the Ibex fix, so we should probably have a compiler flag to disable it that we can add to the build system.

I believe `-mllvm -disable-global-outlining` should suffice
